//  storeIndexPage
export const CHANGE_ASIDE_SEARCH_SHOW_FLAG = 'CHANGE_ASIDE_SEARCH_SHOW_FLAG'
export const CHANGE_ASIDE_SHOW_FLAG = 'CHANGE_ASIDE_SHOW_FLAG'
export const CHANGE_FOOTER_TABBAR_INDEX = 'CHANGE_FOOTER_TABBAR_INDEX'

export const CHANGE_LOADING_FLAG = 'CHANGE_LOADING_FLAG'
export const RECEIVE_TOPTEN = 'RECEIVE_TOPTEN'
export const RECEIVE_IDLIST = 'RECEIVE_IDLIST'

export const RECEIVE_HP = 'RECEIVE_HP'

export const RECEIVE_ESSAY = 'RECEIVE_ESSAY'
export const RECEIVE_SERIAL = 'RECEIVE_SERIAL'
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'

export const RECEIVE_NEXTPAGE = 'RECEIVE_NEXTPAGE'

export const RECEIVE_MUSIC = 'RECEIVE_MUSIC'
export const RECEIVE_MUSIC_URL = 'RECEIVE_MUSIC_URL'
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE'
export const RECEIVE_MOVIE_PHOTOS = 'RECEIVE_MOVIE_PHOTOS'
export const CLEAN_MOVIE_PHOTOS = 'CLEAN_MOVIE_PHOTOS'

export const WEATHER = 'WEATHER'

//  storeSportsDetail
export const CHANGE_DETAIL_CALORIE_TIME = 'CHANGE_DETAIL_CALORIE_TIME'

// storeCalenderSportsSteps
export const CHANGE_CALENDER_STEPS = 'CHANGE_CALENDER_STEPS'

// storeDraggableComponent
export const CHANGE_SHOW_COM_LIST = 'CHANGE_SHOW_COM_LIST'
export const CHANGE_HIDE_COM_LIST = 'CHANGE_HIDE_COM_LIST'
export const CHANGE_SHOW_SIDE_BAR = 'CHANGE_SHOW_SIDE_BAR'

// storeHeadTitle
export const CHANGE_SHOW_CONTEXT_PAGE = 'CHANGE_SHOW_CONTEXT_PAGE'
